"""init

Revision ID: 1b3e0ab69897
Revises: 
Create Date: 2021-08-05 19:32:14.745926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b3e0ab69897'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_channels',
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('telegram_id', sa.String(), nullable=False),
    sa.Column('added_by', sa.Integer(), nullable=False),
    sa.Column('has_currently_membership', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_telegram_channels_added_by'), 'telegram_channels', ['added_by'], unique=False)
    op.create_index(op.f('ix_telegram_channels_has_currently_membership'), 'telegram_channels', ['has_currently_membership'], unique=False)
    op.create_index(op.f('ix_telegram_channels_telegram_id'), 'telegram_channels', ['telegram_id'], unique=False)
    op.create_table('telegram_channel_scans',
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('channel_uuid', sa.String(length=36), nullable=False),
    sa.Column('dogs_count', sa.Integer(), nullable=True),
    sa.Column('detected_kick', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['channel_uuid'], ['telegram_channels.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telegram_channel_scans')
    op.drop_index(op.f('ix_telegram_channels_telegram_id'), table_name='telegram_channels')
    op.drop_index(op.f('ix_telegram_channels_has_currently_membership'), table_name='telegram_channels')
    op.drop_index(op.f('ix_telegram_channels_added_by'), table_name='telegram_channels')
    op.drop_table('telegram_channels')
    # ### end Alembic commands ###
